import "server-only";

import { mkdir, realpath, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { db } from "@/db";
import { projectFiles, workspaceSettings } from "@/db/schema";
import { eq } from "drizzle-orm";
import { ensureWorkspaceBootstrap, updateWorkspaceSettings } from "@/lib/workspace";
import { connectWorkspaceDirectory } from "@/lib/workspace-files";

export type ProjectTemplateId = "web" | "mobile" | "desktop" | "all" | "telegram";

export const PROJECT_TEMPLATES: Array<{ id: ProjectTemplateId; label: string; description: string }> = [
  { id: "web", label: "🌐 Web-сайт / Веб-приложение", description: "React / Vite / HTML-CSS" },
  { id: "mobile", label: "📱 Мобильное приложение", description: "Capacitor / Android APK / iOS" },
  { id: "desktop", label: "💻 Десктоп-приложение", description: ".exe / Electron" },
  { id: "all", label: "⚡ Мульти-платформа Все в одном", description: "Web + APK + EXE" },
  { id: "telegram", label: "🤖 Telegram-бот / Backend API", description: "Node.js / Express" },
];

const prompts: Record<ProjectTemplateId, string> = {
  web: "Работай как Web UI инженер: учитывай responsive layout, accessibility, Vite/React conventions и визуальную проверку через Live Preview.",
  mobile: "Работай как mobile engineer: учитывай Capacitor, touch targets, safe areas, Android/iOS differences и offline-friendly UX.",
  desktop: "Работай как Electron engineer: учитывай IPC boundaries, preload security, packaging и Windows/macOS/Linux behavior.",
  all: "Работай как cross-platform architect: разделяй web, mobile и desktop layers, переиспользуй shared domain code и проверяй каждый target.",
  telegram: "Работай как Node.js backend engineer: учитывай Telegram Bot API, webhook/polling, validation, rate limits, secrets и observability.",
};

type TemplateFiles = Record<string, string>;

function filesFor(template: ProjectTemplateId): TemplateFiles {
  const common = {
    "README.md": `# Multi-Agent Project\n\nPreset: ${template}\n\nGenerated by Multi-Agent Code Studio.\n`,
    ".gitignore": "node_modules/\ndist/\n.env\n.env.*\n",
  };
  if (template === "telegram") return { ...common, "package.json": JSON.stringify({ name: "telegram-backend", version: "0.1.0", private: true, scripts: { dev: "node src/index.js", start: "node src/index.js" }, dependencies: { express: "latest", "node-telegram-bot-api": "latest" } }, null, 2) + "\n", "src/index.js": "const express = require('express');\nconst app = express();\napp.use(express.json());\napp.get('/health', (_req, res) => res.json({ ok: true }));\napp.listen(process.env.PORT || 4173);\n" };
  if (template === "mobile") return { ...common, "package.json": JSON.stringify({ name: "mobile-app", version: "0.1.0", private: true, scripts: { dev: "vite", build: "vite build" }, dependencies: { "@capacitor/core": "latest", react: "latest", "react-dom": "latest" }, devDependencies: { vite: "latest", "@vitejs/plugin-react": "latest" } }, null, 2) + "\n", "index.html": "<div id=\"root\"></div><script type=\"module\" src=\"/src/main.jsx\"></script>\n", "src/main.jsx": "import React from 'react';\nimport { createRoot } from 'react-dom/client';\ncreateRoot(document.getElementById('root')).render(<main>Mobile app</main>);\n" };
  if (template === "desktop") return { ...common, "package.json": JSON.stringify({ name: "desktop-app", version: "0.1.0", private: true, main: "main.cjs", scripts: { dev: "electron .", start: "electron ." }, devDependencies: { electron: "latest" } }, null, 2) + "\n", "main.cjs": "const { app, BrowserWindow } = require('electron');\napp.whenReady().then(() => { const win = new BrowserWindow({ webPreferences: { contextIsolation: true } }); win.loadURL(process.env.PREVIEW_URL || 'http://localhost:4173'); });\n" };
  if (template === "all") {
    const webFiles = filesFor("web");
    const packageJson = JSON.stringify({
      name: "multi-platform-app",
      version: "0.1.0",
      private: true,
      main: "electron/main.cjs",
      scripts: {
        dev: "vite",
        build: "vite build",
        "desktop:dev": "electron .",
        "mobile:sync": "cap sync",
      },
      dependencies: { react: "latest", "react-dom": "latest", "@capacitor/core": "latest" },
      devDependencies: { vite: "latest", "@vitejs/plugin-react": "latest", "@capacitor/cli": "latest", electron: "latest" },
    }, null, 2) + "\n";
    return { ...webFiles, "package.json": packageJson, "capacitor.config.ts": "import type { CapacitorConfig } from '@capacitor/cli';\nconst config: CapacitorConfig = { appId: 'com.example.app', appName: 'Multi Platform App', webDir: 'dist' };\nexport default config;\n", "electron/main.cjs": "const { app, BrowserWindow } = require('electron');\napp.whenReady().then(() => { const win = new BrowserWindow({ webPreferences: { contextIsolation: true } }); win.loadURL(process.env.PREVIEW_URL || 'http://localhost:4173'); });\n" };
  }
  return { ...common, "package.json": JSON.stringify({ name: "web-app", version: "0.1.0", private: true, scripts: { dev: "vite", build: "vite build" }, dependencies: { react: "latest", "react-dom": "latest" }, devDependencies: { vite: "latest", "@vitejs/plugin-react": "latest" } }, null, 2) + "\n", "index.html": "<div id=\"root\"></div><script type=\"module\" src=\"/src/main.jsx\"></script>\n", "src/main.jsx": "import React from 'react';\nimport { createRoot } from 'react-dom/client';\ncreateRoot(document.getElementById('root')).render(<main>Web app</main>);\n" };
}

export async function generateProjectTemplate(template: ProjectTemplateId, directory: string) {
  await ensureWorkspaceBootstrap();
  const files = filesFor(template);
  const root = await realpath(path.resolve(directory));
  const rootInfo = await stat(root);
  if (!rootInfo.isDirectory()) throw new Error("Template directory must be an existing folder");
  for (const [relative, content] of Object.entries(files)) {
    const target = path.join(root, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, { encoding: "utf8", flag: "wx" }).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== "EEXIST") throw error;
    });
  }
  await connectWorkspaceDirectory(root);
  await updateWorkspaceSettings({ projectTemplate: template, projectTemplatePrompt: prompts[template] });
  const [settings] = await db.select().from(workspaceSettings).limit(1);
  await db.delete(projectFiles).where(eq(projectFiles.path, "__template_placeholder__"));
  return { root, template, prompt: prompts[template], files: Object.keys(files), settingsId: settings?.id ?? null };
}
